[qwen35-9b-ollama-native]
provider = "ollama"
model = "qwen3.5:9b"
temperature = 0.0
tokens = 10000
system_prompt = '''{{ file('examples/prompt/prompt_mcq.md') }}'''
datasets = [ "pubmedqa" ]

[qwen35-9b-ollama-neo4j-embedding-triplet-formal]
provider = "ollama"
model = "qwen3.5:9b"
temperature = 0.0
tokens = 10000
system_prompt = '''{{ file('examples/prompt/pmu_prompt_mcq.md') }}'''
datasets = [ "pubmedqa" ]
augmented_generation = {
  retriever = "neo4j-embedding-triplet-formal",
  database = "neo4j"
}
